### ISSUE TITLE
Figuring out the best way to set up a form for taking an order

### ISSUE THREAD

**Issue by niddy1** [niddy1/RestaurantApp#1]
Right now I have something like this:

```
<form class="food-list" action="/orders" method="post">
  <%@foods.each do |food|%>
  <ul>
    <li name="food[name]" onclick="food-list.submit();"><%=food.name%></li>

  </ul>
  <%end%>
</form>
```

I don't think this will get the job done. It's saying food is not defined, and I haven't factored in grabbing
the params from parties.

I would like a quick sit down to see if there is a better way or if  there is something I'm overlooking.

**Comment by amadden80** [comment]
Hmmmm.   Let's chat for a minute.  I'd suggest either each of the food items being their own `form` or using a different user interface.

What would you think about something like

``` html

<%@foods.each do |food|%>
    <form class="food-list" action="/orders" method="post">
        <input type="hidden" name="order[food_id]" value="<%= food.id %>>
        <button type="submit"><%= food.name %></button>
    </form>
<%end%>

```

Does that work?
