### ISSUE TITLE
Cannot figure out how to get my table links lead to different location based on if condition

### ISSUE THREAD

**Issue by niddy1** [niddy1/RestaurantApp#2]
I'm not sure if this idea will work. And as of now, I have not written it correctly. I am getting a syntax error. 

I want my table links to lead me to a show page of the party IF a party contains a table_number that is equal to the table that was clicked. 

If no party contains that table_number, the link should lead to a create new party page.

```
<%tables=*(1..9)%>
<%tables.each do |table|%>

<%if ( (@parties.find(params[:party][:table_number]) ) == table  %>
    <a href="/parties/1?party[table_number]=<%=table%>">
      <div class="tables three columns"><%=table%></div>
    </a>

    <%else  %>
        <a href="/parties/new?party[table_number]=<%=table%>">
          <div class="tables three columns"><%=table%></div>
        </a>

<%end%>
```

**Comment by emilylordahl** [comment]
What does your syntax error say?

**Comment by rapala61** [comment]
you are missing and `end` section to close the loop

**Comment by niddy1** [comment]
fixed the ends. Hit another error:

NoMethodError at /parties/
undefined method `[]' for nil:NilClass

```
<%if  (@parties.find(params[:party][:table_number]) ) == table  %>

```

**Comment by rapala61** [comment]
take a screenshot of the whole error

**Comment by niddy1** [comment]
![screen shot 2015-08-27 at 3 15 52 pm](https://cloud.githubusercontent.com/assets/12988870/9530559/9f224b32-4cce-11e5-9517-30e63647c6ba.png)

**Comment by amadden80** [comment]
Was this issues resolved?

**Comment by amadden80** [comment]
_in person_
